steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/hackday-ledger/ledger-serverful', '.']
    # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/hackday-ledger/ledger-serverful']
    # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'ledger-serverful', '--image', 'gcr.io/hackday-ledger/ledger-serverful', '--region', 'europe-west1','--platform', 'managed', '--quiet']
images:
  - gcr.io/hackday-ledger/ledger-serverful
