spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql:///ledger
    username: ledger
    password: ledger
    hikari:
      data-source-properties:
        socketFactory: "com.google.cloud.sql.postgres.SocketFactory"
        cloudSqlInstance: "hackday-ledger:europe-west1:ledger-db"
      maximum-pool-size: 5
      minimum-idle: 5
